config/routes.rb
Thatapp::Application.routes.draw do
  
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :games
  resources :questions do
    resources :answers
  end
  resources :game_questions do
    resources :answers do
      get "success"
      get "fail"
    end
  end
  resources :subscribers,   only: [:new, :create]
  
  root to: 'subscribers#new'
	match '/', to: 'subscribers#new'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home',    to: 'static_pages#home'

	match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %> 

    <h1>About Us</h1>
    <p>
      We wanted to use mobile apps for sex ed
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Get in contact with us, go on.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help</h1>
    <p>
      I don't know either!
    </p>

app/views/static_pages/home.html.erb
  <div class="container" style="width: 800px;margin:300px auto;text-align:center">
    <h1 style="font-weight:normal">Let's do something!</h1>
    <div style="margin: 0px auto; width:300px">
    <p><%= link_to "", new_game_path, class: "btn-startplaying" %></p>
    <p><%= link_to "", questions_path, class: "btn-wtf" %></p>
    </div>
  </div>  