config/routes.rb
Thatapp::Application.routes.draw do
  
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :games
  resources :questions do
    resources :answers
  end
  resources :game_questions do
    resources :answers do
      get "success"
      get "fail"
    end
  end
  resources :subscribers,   only: [:new, :create]
  
  root to: 'subscribers#new'
	match '/', to: 'subscribers#new'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home',    to: 'static_pages#home'

	match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	attr_accessible(:email, :name, :password, :password_confirmation, :expert)
	
	has_secure_password
	has_many :microposts, dependent: :destroy
  has_many :games_created, foreign_key: :user_a_id, class_name: 'Game'
  has_many :games_joined, foreign_key: :user_b_id, class_name: 'Game'
	
	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token
	
	validates(:name, presence: true, length: { maximum: 50 })
	validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false })
	validates(:password, presence: true, length: { minimum: 6 })
	validates(:password_confirmation, presence: true)
	
	def random_other_user
    rand_user = nil
    while(rand_user.nil? or rand_user == self or rand_user.admin? or rand_user.expert?) do    
      offset = rand(User.count)
      rand_user = User.first(:offset => offset)
    end
    return rand_user
  end
	
	private

		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_filter :signed_in_user, only: [:index, :edit, :update]
	before_filter :correct_user,   only: [:edit, :update]
	before_filter :admin_user,     only: :destroy
	
	def index
		@users = User.paginate(page: params[:page])
	end
	
	def show
		@user = User.find(params[:id])
		@microposts = @user.microposts.paginate(page: params[:page])
	end
	
	def edit
		#defined in correct_user
    #@user = User.find(params[:id])
  end
	
	def new
		@user = User.new
  end
	
	def create
    @user = User.new(params[:user])
    if @user.save
			sign_in @user
      flash[:success] = "Welcome to That App"
      redirect_to home_path
    else
      render 'new'
    end
  end
	
	def update
    #defined in correct user
		#@user = User.find(params[:id])
    if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated"
			sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
	 
	def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
	
	private
		
		def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
		
		def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def avatar_for(avatar_num, size=nil)
    #gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    #gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    #image_tag("#{user.avatar}.png", alt: user.name, width: size, class: "avatar")
    content_tag("div", "", class: "avatar avatar#{avatar_num}");
  end
end

app/views/users/_expert.html.erb
<div class="expert">
Answered by:
  <%= avatar_for user %> <%= user.name %>
</div>

app/views/users/_fields.html.erb
<%= render "shared/error_messages", object: f.object %>
      
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= avatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  <%= link_to "Start game", games_path(user_b_id: user.id), method: :post %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render "fields", f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
			<%= render "fields", f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= avatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
	<div class="span8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>