config/routes.rb
Thatapp::Application.routes.draw do
  
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :games
  resources :questions do
    resources :answers
  end
  resources :game_questions do
    resources :answers do
      get "success"
      get "fail"
    end
  end
  resources :subscribers,   only: [:new, :create]
  
  root to: 'subscribers#new'
	match '/', to: 'subscribers#new'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home',    to: 'static_pages#home'

	match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Social Innovation Camp Asia 2012
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to root_path do %>
        <%= image_tag "/assets/thatapp_logo.png", width: 50, id: "logo" %>
      <% end %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", home_path %></li>          
          <% if signed_in? %>
            <li class="<%= games_link_class current_user%>"><%= link_to "Games", games_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%=current_user.name%> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>that app..</title>
  <%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css", media: "all" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Patrick+Hand", media: "all" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36362099-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
</head>
<body>
    <%= render "layouts/header" %>
    <div class="container">
			<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
     <%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
<div id="social_media" class="pull-left"><a href="http://www.facebook.com/ThatApp.sh" class="btn btn-primary" alt="Check us out on facebook"><i class='icon-facebook-sign icon-large'></i></a></div>
</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Patrick+Hand", media: "all" %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>    
  </head>
  <body>
      <%= yield %>
		</div>
  </body>
</html>